/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Factorynew4.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.49, 1.28, 0.59]} scale={1.29}>
        <mesh geometry={nodes.Cube001.geometry} material={materials['Material.002']} onClick={(e) => { e.stopPropagation(); props.getClickevent('cam1'); }} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} onClick={(e) => { e.stopPropagation(); props.getClickevent('cam2') }} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.001']} onClick={(e) => { e.stopPropagation(); props.getClickevent('cam3') }}>
          <meshBasicMaterial
            attach="material"
            color="green" 
          />
        </mesh>
        <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.004']} onClick={(e) => { e.stopPropagation(); props.getClickevent('cam4') }} />
        <mesh
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[-0.38, -1, -0.46]}
          scale={2.52}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Factorynew4.glb')
